name: "Terraform — Dev"

on:
  push:
    branches-ignore: [ "main" ]   # todas menos main
    paths:
      - "**"                      # aplica a todo el repo
  workflow_dispatch: {}

permissions:
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  dev:
    runs-on: ubuntu-latest
    name: Terraform Dev (plan + apply)
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          terraform_wrapper: false

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan (dev)
        run: terraform plan -input=false -var-file=terraform.local.dev.tfvars -out=tfplan-dev

      - name: Terraform Apply (dev)
        run: terraform apply -input=false -auto-approve -var-file=terraform.local.dev.tfvars
